// Automatically generated by odin 1.5.11 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
typedef struct sir_base_internal {
  double beta;
  int dim_I;
  int dim_N;
  int dim_n_IR;
  int dim_n_SI;
  int dim_p_SI;
  int dim_R;
  int dim_S;
  int dim_S_inc;
  double dt;
  double gamma;
  double I_ini;
  double *initial_I;
  double *initial_R;
  double *initial_S;
  double *initial_S_inc;
  double initial_time;
  double *N;
  double *n_IR;
  double *n_SI;
  int nsim;
  int offset_variable_I;
  int offset_variable_R;
  int offset_variable_S_inc;
  double p_IR;
  double *p_SI;
  double S_ini;
  double steps_per_day;
} sir_base_internal;
typedef struct sir_vaccine_internal {
  double beta;
  double detect_n;
  int dim_B;
  int dim_I;
  int dim_InfectedCNT;
  int dim_InterventionFLG;
  int dim_N;
  int dim_n_BR;
  int dim_n_IB;
  int dim_n_SI;
  int dim_n_SR;
  int dim_p_SI;
  int dim_R;
  int dim_S;
  int dim_S_inc;
  int dim_V_inc;
  double dt;
  double gamma;
  double I_ini;
  double *initial_B;
  double *initial_I;
  double *initial_InfectedCNT;
  double *initial_InterventionFLG;
  double *initial_R;
  double *initial_S;
  double *initial_S_inc;
  double initial_time;
  double *initial_V_inc;
  double intervention_scenario;
  double kappa;
  double *N;
  double *n_BR;
  double *n_IB;
  double *n_SI;
  double *n_SR;
  int nsim;
  int offset_variable_B;
  int offset_variable_I;
  int offset_variable_InfectedCNT;
  int offset_variable_InterventionFLG;
  int offset_variable_R;
  int offset_variable_S_inc;
  int offset_variable_V_inc;
  double p_BR;
  double p_IB;
  double *p_SI;
  double S_ini;
  double steps_per_day;
  double t_intervention;
  double zeta;
} sir_vaccine_internal;
sir_base_internal* sir_base_get_internal(SEXP internal_p, int closed_error);
static void sir_base_finalise(SEXP internal_p);
SEXP sir_base_create(SEXP user);
void sir_base_initmod_desolve(void(* odeparms) (int *, double *));
SEXP sir_base_contents(SEXP internal_p);
SEXP sir_base_set_user(SEXP internal_p, SEXP user);
SEXP sir_base_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr);
SEXP sir_base_metadata(SEXP internal_p);
SEXP sir_base_initial_conditions(SEXP internal_p, SEXP step_ptr);
void sir_base_rhs(sir_base_internal* internal, size_t step, double * state, double * state_next, double * output);
void sir_base_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal);
SEXP sir_base_rhs_r(SEXP internal_p, SEXP step, SEXP state);
sir_vaccine_internal* sir_vaccine_get_internal(SEXP internal_p, int closed_error);
static void sir_vaccine_finalise(SEXP internal_p);
SEXP sir_vaccine_create(SEXP user);
void sir_vaccine_initmod_desolve(void(* odeparms) (int *, double *));
SEXP sir_vaccine_contents(SEXP internal_p);
SEXP sir_vaccine_set_user(SEXP internal_p, SEXP user);
SEXP sir_vaccine_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr);
SEXP sir_vaccine_metadata(SEXP internal_p);
SEXP sir_vaccine_initial_conditions(SEXP internal_p, SEXP step_ptr);
void sir_vaccine_rhs(sir_vaccine_internal* internal, size_t step, double * state, double * state_next, double * output);
void sir_vaccine_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal);
SEXP sir_vaccine_rhs_r(SEXP internal_p, SEXP step, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
double fmodr(double x, double y);
int scalar_int(SEXP x, const char * name);
double odin_sum1(double *x, size_t from, size_t to);
sir_base_internal* sir_base_get_internal(SEXP internal_p, int closed_error) {
  sir_base_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (sir_base_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void sir_base_finalise(SEXP internal_p) {
  sir_base_internal *internal = sir_base_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal->initial_I);
    R_Free(internal->initial_R);
    R_Free(internal->initial_S);
    R_Free(internal->initial_S_inc);
    R_Free(internal->N);
    R_Free(internal->n_IR);
    R_Free(internal->n_SI);
    R_Free(internal->p_SI);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP sir_base_create(SEXP user) {
  sir_base_internal *internal = (sir_base_internal*) R_Calloc(1, sir_base_internal);
  internal->initial_I = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->initial_S_inc = NULL;
  internal->N = NULL;
  internal->n_IR = NULL;
  internal->n_SI = NULL;
  internal->p_SI = NULL;
  internal->initial_time = 0;
  internal->beta = 0.82999999999999996;
  internal->gamma = 0.5;
  internal->I_ini = 1;
  internal->nsim = 500;
  internal->S_ini = 499;
  internal->steps_per_day = 1;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, sir_base_finalise);
  UNPROTECT(1);
  return ptr;
}
static sir_base_internal *sir_base_internal_ds;
void sir_base_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  sir_base_internal_ds = sir_base_get_internal(get_desolve_gparms(), 1);
}
SEXP sir_base_contents(SEXP internal_p) {
  sir_base_internal *internal = sir_base_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 28));
  SET_VECTOR_ELT(contents, 0, ScalarReal(internal->beta));
  SET_VECTOR_ELT(contents, 1, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(contents, 2, ScalarInteger(internal->dim_N));
  SET_VECTOR_ELT(contents, 3, ScalarInteger(internal->dim_n_IR));
  SET_VECTOR_ELT(contents, 4, ScalarInteger(internal->dim_n_SI));
  SET_VECTOR_ELT(contents, 5, ScalarInteger(internal->dim_p_SI));
  SET_VECTOR_ELT(contents, 6, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_S_inc));
  SET_VECTOR_ELT(contents, 9, ScalarReal(internal->dt));
  SET_VECTOR_ELT(contents, 10, ScalarReal(internal->gamma));
  SET_VECTOR_ELT(contents, 11, ScalarReal(internal->I_ini));
  SEXP initial_I = PROTECT(allocVector(REALSXP, internal->dim_I));
  memcpy(REAL(initial_I), internal->initial_I, internal->dim_I * sizeof(double));
  SET_VECTOR_ELT(contents, 12, initial_I);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  SET_VECTOR_ELT(contents, 13, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  SET_VECTOR_ELT(contents, 14, initial_S);
  SEXP initial_S_inc = PROTECT(allocVector(REALSXP, internal->dim_S_inc));
  memcpy(REAL(initial_S_inc), internal->initial_S_inc, internal->dim_S_inc * sizeof(double));
  SET_VECTOR_ELT(contents, 15, initial_S_inc);
  SET_VECTOR_ELT(contents, 16, ScalarReal(internal->initial_time));
  SEXP N = PROTECT(allocVector(REALSXP, internal->dim_N));
  memcpy(REAL(N), internal->N, internal->dim_N * sizeof(double));
  SET_VECTOR_ELT(contents, 17, N);
  SEXP n_IR = PROTECT(allocVector(REALSXP, internal->dim_n_IR));
  memcpy(REAL(n_IR), internal->n_IR, internal->dim_n_IR * sizeof(double));
  SET_VECTOR_ELT(contents, 18, n_IR);
  SEXP n_SI = PROTECT(allocVector(REALSXP, internal->dim_n_SI));
  memcpy(REAL(n_SI), internal->n_SI, internal->dim_n_SI * sizeof(double));
  SET_VECTOR_ELT(contents, 19, n_SI);
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->nsim));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->offset_variable_I));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->offset_variable_R));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->offset_variable_S_inc));
  SET_VECTOR_ELT(contents, 24, ScalarReal(internal->p_IR));
  SEXP p_SI = PROTECT(allocVector(REALSXP, internal->dim_p_SI));
  memcpy(REAL(p_SI), internal->p_SI, internal->dim_p_SI * sizeof(double));
  SET_VECTOR_ELT(contents, 25, p_SI);
  SET_VECTOR_ELT(contents, 26, ScalarReal(internal->S_ini));
  SET_VECTOR_ELT(contents, 27, ScalarReal(internal->steps_per_day));
  SEXP nms = PROTECT(allocVector(STRSXP, 28));
  SET_STRING_ELT(nms, 0, mkChar("beta"));
  SET_STRING_ELT(nms, 1, mkChar("dim_I"));
  SET_STRING_ELT(nms, 2, mkChar("dim_N"));
  SET_STRING_ELT(nms, 3, mkChar("dim_n_IR"));
  SET_STRING_ELT(nms, 4, mkChar("dim_n_SI"));
  SET_STRING_ELT(nms, 5, mkChar("dim_p_SI"));
  SET_STRING_ELT(nms, 6, mkChar("dim_R"));
  SET_STRING_ELT(nms, 7, mkChar("dim_S"));
  SET_STRING_ELT(nms, 8, mkChar("dim_S_inc"));
  SET_STRING_ELT(nms, 9, mkChar("dt"));
  SET_STRING_ELT(nms, 10, mkChar("gamma"));
  SET_STRING_ELT(nms, 11, mkChar("I_ini"));
  SET_STRING_ELT(nms, 12, mkChar("initial_I"));
  SET_STRING_ELT(nms, 13, mkChar("initial_R"));
  SET_STRING_ELT(nms, 14, mkChar("initial_S"));
  SET_STRING_ELT(nms, 15, mkChar("initial_S_inc"));
  SET_STRING_ELT(nms, 16, mkChar("initial_time"));
  SET_STRING_ELT(nms, 17, mkChar("N"));
  SET_STRING_ELT(nms, 18, mkChar("n_IR"));
  SET_STRING_ELT(nms, 19, mkChar("n_SI"));
  SET_STRING_ELT(nms, 20, mkChar("nsim"));
  SET_STRING_ELT(nms, 21, mkChar("offset_variable_I"));
  SET_STRING_ELT(nms, 22, mkChar("offset_variable_R"));
  SET_STRING_ELT(nms, 23, mkChar("offset_variable_S_inc"));
  SET_STRING_ELT(nms, 24, mkChar("p_IR"));
  SET_STRING_ELT(nms, 25, mkChar("p_SI"));
  SET_STRING_ELT(nms, 26, mkChar("S_ini"));
  SET_STRING_ELT(nms, 27, mkChar("steps_per_day"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(10);
  return contents;
}
SEXP sir_base_set_user(SEXP internal_p, SEXP user) {
  sir_base_internal *internal = sir_base_get_internal(internal_p, 1);
  internal->beta = user_get_scalar_double(user, "beta", internal->beta, NA_REAL, NA_REAL);
  internal->gamma = user_get_scalar_double(user, "gamma", internal->gamma, NA_REAL, NA_REAL);
  internal->I_ini = user_get_scalar_double(user, "I_ini", internal->I_ini, NA_REAL, NA_REAL);
  internal->nsim = user_get_scalar_int(user, "nsim", internal->nsim, NA_REAL, NA_REAL);
  internal->S_ini = user_get_scalar_double(user, "S_ini", internal->S_ini, NA_REAL, NA_REAL);
  internal->steps_per_day = user_get_scalar_double(user, "steps_per_day", internal->steps_per_day, NA_REAL, NA_REAL);
  internal->dim_I = internal->nsim;
  internal->dim_N = internal->nsim;
  internal->dim_n_IR = internal->nsim;
  internal->dim_n_SI = internal->nsim;
  internal->dim_p_SI = internal->nsim;
  internal->dim_R = internal->nsim;
  internal->dim_S = internal->nsim;
  internal->dim_S_inc = internal->nsim;
  internal->dt = 1 / (double) internal->steps_per_day;
  internal->p_IR = 1 - exp(-(internal->gamma));
  R_Free(internal->initial_I);
  internal->initial_I = (double*) R_Calloc(internal->dim_I, double);
  R_Free(internal->initial_R);
  internal->initial_R = (double*) R_Calloc(internal->dim_R, double);
  R_Free(internal->initial_S);
  internal->initial_S = (double*) R_Calloc(internal->dim_S, double);
  R_Free(internal->initial_S_inc);
  internal->initial_S_inc = (double*) R_Calloc(internal->dim_S_inc, double);
  R_Free(internal->N);
  internal->N = (double*) R_Calloc(internal->dim_N, double);
  R_Free(internal->n_IR);
  internal->n_IR = (double*) R_Calloc(internal->dim_n_IR, double);
  R_Free(internal->n_SI);
  internal->n_SI = (double*) R_Calloc(internal->dim_n_SI, double);
  R_Free(internal->p_SI);
  internal->p_SI = (double*) R_Calloc(internal->dim_p_SI, double);
  for (int i = 1; i <= internal->dim_I; ++i) {
    internal->initial_I[i - 1] = internal->I_ini;
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    internal->initial_R[i - 1] = 0;
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    internal->initial_S[i - 1] = internal->S_ini;
  }
  for (int i = 1; i <= internal->dim_S_inc; ++i) {
    internal->initial_S_inc[i - 1] = 0;
  }
  internal->offset_variable_I = internal->dim_S + 1;
  internal->offset_variable_R = internal->dim_I + internal->dim_S + 1;
  internal->offset_variable_S_inc = internal->dim_I + internal->dim_R + internal->dim_S + 1;
  return R_NilValue;
}
SEXP sir_base_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr) {
  return R_NilValue;
}
SEXP sir_base_metadata(SEXP internal_p) {
  sir_base_internal *internal = sir_base_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 5));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 5));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, R_NilValue);
  SET_VECTOR_ELT(variable_length, 1, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(variable_length, 2, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(variable_length, 3, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(variable_length, 4, ScalarInteger(internal->dim_S_inc));
  SET_STRING_ELT(variable_names, 0, mkChar("time"));
  SET_STRING_ELT(variable_names, 1, mkChar("S"));
  SET_STRING_ELT(variable_names, 2, mkChar("I"));
  SET_STRING_ELT(variable_names, 3, mkChar("R"));
  SET_STRING_ELT(variable_names, 4, mkChar("S_inc"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 1, R_NilValue);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(0));
  UNPROTECT(2);
  return ret;
}
SEXP sir_base_initial_conditions(SEXP internal_p, SEXP step_ptr) {
  sir_base_internal *internal = sir_base_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_I + internal->dim_R + internal->dim_S + internal->dim_S_inc + 1));
  double * state = REAL(r_state);
  state[0] = internal->initial_time;
  memcpy(state + 1, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->offset_variable_I, internal->initial_I, internal->dim_I * sizeof(double));
  memcpy(state + internal->offset_variable_R, internal->initial_R, internal->dim_R * sizeof(double));
  memcpy(state + internal->offset_variable_S_inc, internal->initial_S_inc, internal->dim_S_inc * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void sir_base_rhs(sir_base_internal* internal, size_t step, double * state, double * state_next, double * output) {
  double * S = state + 1;
  double * I = state + internal->offset_variable_I;
  double * R = state + internal->offset_variable_R;
  double * S_inc = state + internal->offset_variable_S_inc;
  state_next[0] = (step + 1) * internal->dt;
  for (int i = 1; i <= internal->dim_N; ++i) {
    internal->N[i - 1] = S[i - 1] + I[i - 1] + R[i - 1];
  }
  for (int i = 1; i <= internal->dim_n_IR; ++i) {
    internal->n_IR[i - 1] = Rf_rbinom(round(I[i - 1]), internal->p_IR * internal->dt);
  }
  for (int i = 1; i <= internal->dim_p_SI; ++i) {
    internal->p_SI[i - 1] = 1 - exp(-(internal->beta) * I[i - 1] / (double) internal->N[i - 1]);
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    state_next[internal->offset_variable_R + i - 1] = R[i - 1] + internal->n_IR[i - 1];
  }
  for (int i = 1; i <= internal->dim_n_SI; ++i) {
    internal->n_SI[i - 1] = Rf_rbinom(round(S[i - 1]), internal->p_SI[i - 1] * internal->dt);
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    state_next[internal->offset_variable_I + i - 1] = I[i - 1] + internal->n_SI[i - 1] - internal->n_IR[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    state_next[1 + i - 1] = S[i - 1] - internal->n_SI[i - 1];
  }
  for (int i = 1; i <= internal->dim_S_inc; ++i) {
    state_next[internal->offset_variable_S_inc + i - 1] = (fmodr(step, internal->steps_per_day) == 0 ? internal->n_SI[i - 1] : S_inc[i - 1] + internal->n_SI[i - 1]);
  }
}
void sir_base_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal) {
  sir_base_rhs((sir_base_internal*)internal, step, state, state_next, output);
}
SEXP sir_base_rhs_r(SEXP internal_p, SEXP step, SEXP state) {
  SEXP state_next = PROTECT(allocVector(REALSXP, LENGTH(state)));
  sir_base_internal *internal = sir_base_get_internal(internal_p, 1);
  double *output = NULL;
  GetRNGstate();
  sir_base_rhs(internal, scalar_int(step, "step"), REAL(state), REAL(state_next), output);
  PutRNGstate();
  UNPROTECT(1);
  return state_next;
}
sir_vaccine_internal* sir_vaccine_get_internal(SEXP internal_p, int closed_error) {
  sir_vaccine_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (sir_vaccine_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void sir_vaccine_finalise(SEXP internal_p) {
  sir_vaccine_internal *internal = sir_vaccine_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal->initial_B);
    R_Free(internal->initial_I);
    R_Free(internal->initial_InfectedCNT);
    R_Free(internal->initial_InterventionFLG);
    R_Free(internal->initial_R);
    R_Free(internal->initial_S);
    R_Free(internal->initial_S_inc);
    R_Free(internal->initial_V_inc);
    R_Free(internal->N);
    R_Free(internal->n_BR);
    R_Free(internal->n_IB);
    R_Free(internal->n_SI);
    R_Free(internal->n_SR);
    R_Free(internal->p_SI);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP sir_vaccine_create(SEXP user) {
  sir_vaccine_internal *internal = (sir_vaccine_internal*) R_Calloc(1, sir_vaccine_internal);
  internal->initial_B = NULL;
  internal->initial_I = NULL;
  internal->initial_InfectedCNT = NULL;
  internal->initial_InterventionFLG = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->initial_S_inc = NULL;
  internal->initial_V_inc = NULL;
  internal->N = NULL;
  internal->n_BR = NULL;
  internal->n_IB = NULL;
  internal->n_SI = NULL;
  internal->n_SR = NULL;
  internal->p_SI = NULL;
  internal->initial_time = 0;
  internal->beta = 1.4199999999999999;
  internal->detect_n = 1;
  internal->gamma = 0.56999999999999995;
  internal->I_ini = 1;
  internal->intervention_scenario = 1;
  internal->kappa = 0.14299999999999999;
  internal->nsim = 500;
  internal->S_ini = 499;
  internal->steps_per_day = 1;
  internal->t_intervention = 10;
  internal->zeta = 0.10000000000000001;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, sir_vaccine_finalise);
  UNPROTECT(1);
  return ptr;
}
static sir_vaccine_internal *sir_vaccine_internal_ds;
void sir_vaccine_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  sir_vaccine_internal_ds = sir_vaccine_get_internal(get_desolve_gparms(), 1);
}
SEXP sir_vaccine_contents(SEXP internal_p) {
  sir_vaccine_internal *internal = sir_vaccine_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 50));
  SET_VECTOR_ELT(contents, 0, ScalarReal(internal->beta));
  SET_VECTOR_ELT(contents, 1, ScalarReal(internal->detect_n));
  SET_VECTOR_ELT(contents, 2, ScalarInteger(internal->dim_B));
  SET_VECTOR_ELT(contents, 3, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(contents, 4, ScalarInteger(internal->dim_InfectedCNT));
  SET_VECTOR_ELT(contents, 5, ScalarInteger(internal->dim_InterventionFLG));
  SET_VECTOR_ELT(contents, 6, ScalarInteger(internal->dim_N));
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_n_BR));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_n_IB));
  SET_VECTOR_ELT(contents, 9, ScalarInteger(internal->dim_n_SI));
  SET_VECTOR_ELT(contents, 10, ScalarInteger(internal->dim_n_SR));
  SET_VECTOR_ELT(contents, 11, ScalarInteger(internal->dim_p_SI));
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_S_inc));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_V_inc));
  SET_VECTOR_ELT(contents, 16, ScalarReal(internal->dt));
  SET_VECTOR_ELT(contents, 17, ScalarReal(internal->gamma));
  SET_VECTOR_ELT(contents, 18, ScalarReal(internal->I_ini));
  SEXP initial_B = PROTECT(allocVector(REALSXP, internal->dim_B));
  memcpy(REAL(initial_B), internal->initial_B, internal->dim_B * sizeof(double));
  SET_VECTOR_ELT(contents, 19, initial_B);
  SEXP initial_I = PROTECT(allocVector(REALSXP, internal->dim_I));
  memcpy(REAL(initial_I), internal->initial_I, internal->dim_I * sizeof(double));
  SET_VECTOR_ELT(contents, 20, initial_I);
  SEXP initial_InfectedCNT = PROTECT(allocVector(REALSXP, internal->dim_InfectedCNT));
  memcpy(REAL(initial_InfectedCNT), internal->initial_InfectedCNT, internal->dim_InfectedCNT * sizeof(double));
  SET_VECTOR_ELT(contents, 21, initial_InfectedCNT);
  SEXP initial_InterventionFLG = PROTECT(allocVector(REALSXP, internal->dim_InterventionFLG));
  memcpy(REAL(initial_InterventionFLG), internal->initial_InterventionFLG, internal->dim_InterventionFLG * sizeof(double));
  SET_VECTOR_ELT(contents, 22, initial_InterventionFLG);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  SET_VECTOR_ELT(contents, 23, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  SET_VECTOR_ELT(contents, 24, initial_S);
  SEXP initial_S_inc = PROTECT(allocVector(REALSXP, internal->dim_S_inc));
  memcpy(REAL(initial_S_inc), internal->initial_S_inc, internal->dim_S_inc * sizeof(double));
  SET_VECTOR_ELT(contents, 25, initial_S_inc);
  SET_VECTOR_ELT(contents, 26, ScalarReal(internal->initial_time));
  SEXP initial_V_inc = PROTECT(allocVector(REALSXP, internal->dim_V_inc));
  memcpy(REAL(initial_V_inc), internal->initial_V_inc, internal->dim_V_inc * sizeof(double));
  SET_VECTOR_ELT(contents, 27, initial_V_inc);
  SET_VECTOR_ELT(contents, 28, ScalarReal(internal->intervention_scenario));
  SET_VECTOR_ELT(contents, 29, ScalarReal(internal->kappa));
  SEXP N = PROTECT(allocVector(REALSXP, internal->dim_N));
  memcpy(REAL(N), internal->N, internal->dim_N * sizeof(double));
  SET_VECTOR_ELT(contents, 30, N);
  SEXP n_BR = PROTECT(allocVector(REALSXP, internal->dim_n_BR));
  memcpy(REAL(n_BR), internal->n_BR, internal->dim_n_BR * sizeof(double));
  SET_VECTOR_ELT(contents, 31, n_BR);
  SEXP n_IB = PROTECT(allocVector(REALSXP, internal->dim_n_IB));
  memcpy(REAL(n_IB), internal->n_IB, internal->dim_n_IB * sizeof(double));
  SET_VECTOR_ELT(contents, 32, n_IB);
  SEXP n_SI = PROTECT(allocVector(REALSXP, internal->dim_n_SI));
  memcpy(REAL(n_SI), internal->n_SI, internal->dim_n_SI * sizeof(double));
  SET_VECTOR_ELT(contents, 33, n_SI);
  SEXP n_SR = PROTECT(allocVector(REALSXP, internal->dim_n_SR));
  memcpy(REAL(n_SR), internal->n_SR, internal->dim_n_SR * sizeof(double));
  SET_VECTOR_ELT(contents, 34, n_SR);
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->nsim));
  SET_VECTOR_ELT(contents, 36, ScalarInteger(internal->offset_variable_B));
  SET_VECTOR_ELT(contents, 37, ScalarInteger(internal->offset_variable_I));
  SET_VECTOR_ELT(contents, 38, ScalarInteger(internal->offset_variable_InfectedCNT));
  SET_VECTOR_ELT(contents, 39, ScalarInteger(internal->offset_variable_InterventionFLG));
  SET_VECTOR_ELT(contents, 40, ScalarInteger(internal->offset_variable_R));
  SET_VECTOR_ELT(contents, 41, ScalarInteger(internal->offset_variable_S_inc));
  SET_VECTOR_ELT(contents, 42, ScalarInteger(internal->offset_variable_V_inc));
  SET_VECTOR_ELT(contents, 43, ScalarReal(internal->p_BR));
  SET_VECTOR_ELT(contents, 44, ScalarReal(internal->p_IB));
  SEXP p_SI = PROTECT(allocVector(REALSXP, internal->dim_p_SI));
  memcpy(REAL(p_SI), internal->p_SI, internal->dim_p_SI * sizeof(double));
  SET_VECTOR_ELT(contents, 45, p_SI);
  SET_VECTOR_ELT(contents, 46, ScalarReal(internal->S_ini));
  SET_VECTOR_ELT(contents, 47, ScalarReal(internal->steps_per_day));
  SET_VECTOR_ELT(contents, 48, ScalarReal(internal->t_intervention));
  SET_VECTOR_ELT(contents, 49, ScalarReal(internal->zeta));
  SEXP nms = PROTECT(allocVector(STRSXP, 50));
  SET_STRING_ELT(nms, 0, mkChar("beta"));
  SET_STRING_ELT(nms, 1, mkChar("detect_n"));
  SET_STRING_ELT(nms, 2, mkChar("dim_B"));
  SET_STRING_ELT(nms, 3, mkChar("dim_I"));
  SET_STRING_ELT(nms, 4, mkChar("dim_InfectedCNT"));
  SET_STRING_ELT(nms, 5, mkChar("dim_InterventionFLG"));
  SET_STRING_ELT(nms, 6, mkChar("dim_N"));
  SET_STRING_ELT(nms, 7, mkChar("dim_n_BR"));
  SET_STRING_ELT(nms, 8, mkChar("dim_n_IB"));
  SET_STRING_ELT(nms, 9, mkChar("dim_n_SI"));
  SET_STRING_ELT(nms, 10, mkChar("dim_n_SR"));
  SET_STRING_ELT(nms, 11, mkChar("dim_p_SI"));
  SET_STRING_ELT(nms, 12, mkChar("dim_R"));
  SET_STRING_ELT(nms, 13, mkChar("dim_S"));
  SET_STRING_ELT(nms, 14, mkChar("dim_S_inc"));
  SET_STRING_ELT(nms, 15, mkChar("dim_V_inc"));
  SET_STRING_ELT(nms, 16, mkChar("dt"));
  SET_STRING_ELT(nms, 17, mkChar("gamma"));
  SET_STRING_ELT(nms, 18, mkChar("I_ini"));
  SET_STRING_ELT(nms, 19, mkChar("initial_B"));
  SET_STRING_ELT(nms, 20, mkChar("initial_I"));
  SET_STRING_ELT(nms, 21, mkChar("initial_InfectedCNT"));
  SET_STRING_ELT(nms, 22, mkChar("initial_InterventionFLG"));
  SET_STRING_ELT(nms, 23, mkChar("initial_R"));
  SET_STRING_ELT(nms, 24, mkChar("initial_S"));
  SET_STRING_ELT(nms, 25, mkChar("initial_S_inc"));
  SET_STRING_ELT(nms, 26, mkChar("initial_time"));
  SET_STRING_ELT(nms, 27, mkChar("initial_V_inc"));
  SET_STRING_ELT(nms, 28, mkChar("intervention_scenario"));
  SET_STRING_ELT(nms, 29, mkChar("kappa"));
  SET_STRING_ELT(nms, 30, mkChar("N"));
  SET_STRING_ELT(nms, 31, mkChar("n_BR"));
  SET_STRING_ELT(nms, 32, mkChar("n_IB"));
  SET_STRING_ELT(nms, 33, mkChar("n_SI"));
  SET_STRING_ELT(nms, 34, mkChar("n_SR"));
  SET_STRING_ELT(nms, 35, mkChar("nsim"));
  SET_STRING_ELT(nms, 36, mkChar("offset_variable_B"));
  SET_STRING_ELT(nms, 37, mkChar("offset_variable_I"));
  SET_STRING_ELT(nms, 38, mkChar("offset_variable_InfectedCNT"));
  SET_STRING_ELT(nms, 39, mkChar("offset_variable_InterventionFLG"));
  SET_STRING_ELT(nms, 40, mkChar("offset_variable_R"));
  SET_STRING_ELT(nms, 41, mkChar("offset_variable_S_inc"));
  SET_STRING_ELT(nms, 42, mkChar("offset_variable_V_inc"));
  SET_STRING_ELT(nms, 43, mkChar("p_BR"));
  SET_STRING_ELT(nms, 44, mkChar("p_IB"));
  SET_STRING_ELT(nms, 45, mkChar("p_SI"));
  SET_STRING_ELT(nms, 46, mkChar("S_ini"));
  SET_STRING_ELT(nms, 47, mkChar("steps_per_day"));
  SET_STRING_ELT(nms, 48, mkChar("t_intervention"));
  SET_STRING_ELT(nms, 49, mkChar("zeta"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(16);
  return contents;
}
SEXP sir_vaccine_set_user(SEXP internal_p, SEXP user) {
  sir_vaccine_internal *internal = sir_vaccine_get_internal(internal_p, 1);
  internal->beta = user_get_scalar_double(user, "beta", internal->beta, NA_REAL, NA_REAL);
  internal->detect_n = user_get_scalar_double(user, "detect_n", internal->detect_n, NA_REAL, NA_REAL);
  internal->gamma = user_get_scalar_double(user, "gamma", internal->gamma, NA_REAL, NA_REAL);
  internal->I_ini = user_get_scalar_double(user, "I_ini", internal->I_ini, NA_REAL, NA_REAL);
  internal->intervention_scenario = user_get_scalar_double(user, "intervention_scenario", internal->intervention_scenario, NA_REAL, NA_REAL);
  internal->kappa = user_get_scalar_double(user, "kappa", internal->kappa, NA_REAL, NA_REAL);
  internal->nsim = user_get_scalar_int(user, "nsim", internal->nsim, NA_REAL, NA_REAL);
  internal->S_ini = user_get_scalar_double(user, "S_ini", internal->S_ini, NA_REAL, NA_REAL);
  internal->steps_per_day = user_get_scalar_double(user, "steps_per_day", internal->steps_per_day, NA_REAL, NA_REAL);
  internal->t_intervention = user_get_scalar_double(user, "t_intervention", internal->t_intervention, NA_REAL, NA_REAL);
  internal->zeta = user_get_scalar_double(user, "zeta", internal->zeta, NA_REAL, NA_REAL);
  internal->dim_B = internal->nsim;
  internal->dim_I = internal->nsim;
  internal->dim_InfectedCNT = internal->nsim;
  internal->dim_InterventionFLG = internal->nsim;
  internal->dim_N = internal->nsim;
  internal->dim_n_BR = internal->nsim;
  internal->dim_n_IB = internal->nsim;
  internal->dim_n_SI = internal->nsim;
  internal->dim_n_SR = internal->nsim;
  internal->dim_p_SI = internal->nsim;
  internal->dim_R = internal->nsim;
  internal->dim_S = internal->nsim;
  internal->dim_S_inc = internal->nsim;
  internal->dim_V_inc = internal->nsim;
  internal->dt = 1 / (double) internal->steps_per_day;
  internal->p_BR = 1 - exp(-(internal->kappa));
  internal->p_IB = 1 - exp(-(internal->gamma));
  R_Free(internal->initial_B);
  internal->initial_B = (double*) R_Calloc(internal->dim_B, double);
  R_Free(internal->initial_I);
  internal->initial_I = (double*) R_Calloc(internal->dim_I, double);
  R_Free(internal->initial_InfectedCNT);
  internal->initial_InfectedCNT = (double*) R_Calloc(internal->dim_InfectedCNT, double);
  R_Free(internal->initial_InterventionFLG);
  internal->initial_InterventionFLG = (double*) R_Calloc(internal->dim_InterventionFLG, double);
  R_Free(internal->initial_R);
  internal->initial_R = (double*) R_Calloc(internal->dim_R, double);
  R_Free(internal->initial_S);
  internal->initial_S = (double*) R_Calloc(internal->dim_S, double);
  R_Free(internal->initial_S_inc);
  internal->initial_S_inc = (double*) R_Calloc(internal->dim_S_inc, double);
  R_Free(internal->initial_V_inc);
  internal->initial_V_inc = (double*) R_Calloc(internal->dim_V_inc, double);
  R_Free(internal->N);
  internal->N = (double*) R_Calloc(internal->dim_N, double);
  R_Free(internal->n_BR);
  internal->n_BR = (double*) R_Calloc(internal->dim_n_BR, double);
  R_Free(internal->n_IB);
  internal->n_IB = (double*) R_Calloc(internal->dim_n_IB, double);
  R_Free(internal->n_SI);
  internal->n_SI = (double*) R_Calloc(internal->dim_n_SI, double);
  R_Free(internal->n_SR);
  internal->n_SR = (double*) R_Calloc(internal->dim_n_SR, double);
  R_Free(internal->p_SI);
  internal->p_SI = (double*) R_Calloc(internal->dim_p_SI, double);
  for (int i = 1; i <= internal->dim_B; ++i) {
    internal->initial_B[i - 1] = 0;
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    internal->initial_I[i - 1] = internal->I_ini;
  }
  for (int i = 1; i <= internal->dim_InfectedCNT; ++i) {
    internal->initial_InfectedCNT[i - 1] = 0;
  }
  for (int i = 1; i <= internal->dim_InterventionFLG; ++i) {
    internal->initial_InterventionFLG[i - 1] = 0;
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    internal->initial_R[i - 1] = 0;
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    internal->initial_S[i - 1] = internal->S_ini;
  }
  for (int i = 1; i <= internal->dim_S_inc; ++i) {
    internal->initial_S_inc[i - 1] = 0;
  }
  for (int i = 1; i <= internal->dim_V_inc; ++i) {
    internal->initial_V_inc[i - 1] = 0;
  }
  internal->offset_variable_B = internal->dim_I + internal->dim_S + 1;
  internal->offset_variable_I = internal->dim_S + 1;
  internal->offset_variable_InfectedCNT = internal->dim_B + internal->dim_I + internal->dim_R + internal->dim_S + internal->dim_S_inc + internal->dim_V_inc + 1;
  internal->offset_variable_InterventionFLG = internal->dim_B + internal->dim_I + internal->dim_InfectedCNT + internal->dim_R + internal->dim_S + internal->dim_S_inc + internal->dim_V_inc + 1;
  internal->offset_variable_R = internal->dim_B + internal->dim_I + internal->dim_S + 1;
  internal->offset_variable_S_inc = internal->dim_B + internal->dim_I + internal->dim_R + internal->dim_S + 1;
  internal->offset_variable_V_inc = internal->dim_B + internal->dim_I + internal->dim_R + internal->dim_S + internal->dim_S_inc + 1;
  return R_NilValue;
}
SEXP sir_vaccine_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr) {
  return R_NilValue;
}
SEXP sir_vaccine_metadata(SEXP internal_p) {
  sir_vaccine_internal *internal = sir_vaccine_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 9));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 9));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, R_NilValue);
  SET_VECTOR_ELT(variable_length, 1, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(variable_length, 2, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(variable_length, 3, ScalarInteger(internal->dim_B));
  SET_VECTOR_ELT(variable_length, 4, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(variable_length, 5, ScalarInteger(internal->dim_S_inc));
  SET_VECTOR_ELT(variable_length, 6, ScalarInteger(internal->dim_V_inc));
  SET_VECTOR_ELT(variable_length, 7, ScalarInteger(internal->dim_InfectedCNT));
  SET_VECTOR_ELT(variable_length, 8, ScalarInteger(internal->dim_InterventionFLG));
  SET_STRING_ELT(variable_names, 0, mkChar("time"));
  SET_STRING_ELT(variable_names, 1, mkChar("S"));
  SET_STRING_ELT(variable_names, 2, mkChar("I"));
  SET_STRING_ELT(variable_names, 3, mkChar("B"));
  SET_STRING_ELT(variable_names, 4, mkChar("R"));
  SET_STRING_ELT(variable_names, 5, mkChar("S_inc"));
  SET_STRING_ELT(variable_names, 6, mkChar("V_inc"));
  SET_STRING_ELT(variable_names, 7, mkChar("InfectedCNT"));
  SET_STRING_ELT(variable_names, 8, mkChar("InterventionFLG"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 1, R_NilValue);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(0));
  UNPROTECT(2);
  return ret;
}
SEXP sir_vaccine_initial_conditions(SEXP internal_p, SEXP step_ptr) {
  sir_vaccine_internal *internal = sir_vaccine_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_B + internal->dim_I + internal->dim_InfectedCNT + internal->dim_InterventionFLG + internal->dim_R + internal->dim_S + internal->dim_S_inc + internal->dim_V_inc + 1));
  double * state = REAL(r_state);
  state[0] = internal->initial_time;
  memcpy(state + 1, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->offset_variable_I, internal->initial_I, internal->dim_I * sizeof(double));
  memcpy(state + internal->offset_variable_B, internal->initial_B, internal->dim_B * sizeof(double));
  memcpy(state + internal->offset_variable_R, internal->initial_R, internal->dim_R * sizeof(double));
  memcpy(state + internal->offset_variable_S_inc, internal->initial_S_inc, internal->dim_S_inc * sizeof(double));
  memcpy(state + internal->offset_variable_V_inc, internal->initial_V_inc, internal->dim_V_inc * sizeof(double));
  memcpy(state + internal->offset_variable_InfectedCNT, internal->initial_InfectedCNT, internal->dim_InfectedCNT * sizeof(double));
  memcpy(state + internal->offset_variable_InterventionFLG, internal->initial_InterventionFLG, internal->dim_InterventionFLG * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void sir_vaccine_rhs(sir_vaccine_internal* internal, size_t step, double * state, double * state_next, double * output) {
  double time = state[0];
  double * S = state + 1;
  double * I = state + internal->offset_variable_I;
  double * B = state + internal->offset_variable_B;
  double * R = state + internal->offset_variable_R;
  double * S_inc = state + internal->offset_variable_S_inc;
  double * V_inc = state + internal->offset_variable_V_inc;
  double * InfectedCNT = state + internal->offset_variable_InfectedCNT;
  double p_SR_int1 = ((int) (time) > (int) (internal->t_intervention) ? 1 - exp(-(internal->zeta)) : 0);
  double p_SR_int2 = (odin_sum1(S_inc, (int) (1) - 1, (int) (time)) > internal->detect_n ? 1 - exp(-(internal->zeta)) : 0);
  double p_SR = (internal->intervention_scenario > 1 ? p_SR_int2 : p_SR_int1);
  state_next[0] = (step + 1) * internal->dt;
  for (int i = 1; i <= internal->dim_N; ++i) {
    internal->N[i - 1] = S[i - 1] + I[i - 1] + B[i - 1] + R[i - 1];
  }
  for (int i = 1; i <= internal->dim_n_BR; ++i) {
    internal->n_BR[i - 1] = Rf_rbinom(round(B[i - 1]), internal->p_BR * internal->dt);
  }
  for (int i = 1; i <= internal->dim_n_IB; ++i) {
    internal->n_IB[i - 1] = Rf_rbinom(round(I[i - 1]), internal->p_IB * internal->dt);
  }
  for (int i = 1; i <= internal->dim_n_SR; ++i) {
    internal->n_SR[i - 1] = Rf_rbinom(round(S[i - 1]), p_SR * internal->dt);
  }
  for (int i = 1; i <= internal->dim_InterventionFLG; ++i) {
    state_next[internal->offset_variable_InterventionFLG + i - 1] = p_SR;
  }
  for (int i = 1; i <= internal->dim_p_SI; ++i) {
    internal->p_SI[i - 1] = 1 - exp(-(internal->beta) * I[i - 1] / (double) internal->N[i - 1]);
  }
  for (int i = 1; i <= internal->dim_B; ++i) {
    state_next[internal->offset_variable_B + i - 1] = B[i - 1] + internal->n_IB[i - 1] - internal->n_BR[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    state_next[internal->offset_variable_R + i - 1] = R[i - 1] + internal->n_BR[i - 1] + internal->n_SR[i - 1];
  }
  for (int i = 1; i <= internal->dim_V_inc; ++i) {
    state_next[internal->offset_variable_V_inc + i - 1] = (fmodr(step, internal->steps_per_day) == 0 ? internal->n_SR[i - 1] : V_inc[i - 1] + internal->n_SR[i - 1]);
  }
  for (int i = 1; i <= internal->dim_n_SI; ++i) {
    internal->n_SI[i - 1] = Rf_rbinom(round(S[i - 1]), internal->p_SI[i - 1] * internal->dt);
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    state_next[internal->offset_variable_I + i - 1] = I[i - 1] + internal->n_SI[i - 1] - internal->n_IB[i - 1];
  }
  for (int i = 1; i <= internal->dim_InfectedCNT; ++i) {
    state_next[internal->offset_variable_InfectedCNT + i - 1] = (fmodr(step, internal->steps_per_day) == 0 ? InfectedCNT[i - 1] + internal->n_SI[i - 1] : InfectedCNT[i - 1] + internal->n_SI[i - 1]);
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    state_next[1 + i - 1] = S[i - 1] - internal->n_SI[i - 1] - internal->n_SR[i - 1];
  }
  for (int i = 1; i <= internal->dim_S_inc; ++i) {
    state_next[internal->offset_variable_S_inc + i - 1] = (fmodr(step, internal->steps_per_day) == 0 ? internal->n_SI[i - 1] : S_inc[i - 1] + internal->n_SI[i - 1]);
  }
}
void sir_vaccine_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal) {
  sir_vaccine_rhs((sir_vaccine_internal*)internal, step, state, state_next, output);
}
SEXP sir_vaccine_rhs_r(SEXP internal_p, SEXP step, SEXP state) {
  SEXP state_next = PROTECT(allocVector(REALSXP, LENGTH(state)));
  sir_vaccine_internal *internal = sir_vaccine_get_internal(internal_p, 1);
  double *output = NULL;
  GetRNGstate();
  sir_vaccine_rhs(internal, scalar_int(step, "step"), REAL(state), REAL(state_next), output);
  PutRNGstate();
  UNPROTECT(1);
  return state_next;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
double fmodr(double x, double y) {
  double tmp = fmod(x, y);
  if (tmp * y < 0) {
    tmp += y;
  }
  return tmp;
}
int scalar_int(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  int ret = 0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    double rx = REAL(x)[0];
    ret = rx;
    if (fabs(rx - ret) > sqrt(DBL_EPSILON)) {
      Rf_error("Expected a integer-like for '%s'", name);
    }
  } else {
    Rf_error("Expected an integer value for '%s'", name);
  }
  return ret;
}
double odin_sum1(double *x, size_t from, size_t to) {
  double tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
