## Automatically generated by odin 1.5.11 - do not edit
sir_base_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "sir_base_rhs_dde"),
    dll = "h5n1speed",
    user = c("beta", "gamma", "I_ini", "nsim", "S_ini", "steps_per_day"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("sir_base_rhs_dde", package = "h5n1speed")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("sir_base_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "h5n1speed")
    },

    update_metadata = function() {
      meta <- .Call("sir_base_metadata", private$ptr,
                    PACKAGE = "h5n1speed")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("sir_base_create", user, PACKAGE = "h5n1speed")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/sir_base.json", mustWork = TRUE,
                             package = "h5n1speed")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("sir_base_set_user", private$ptr, user, PACKAGE = "h5n1speed")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("sir_base_initial_conditions", private$ptr, step, PACKAGE = "h5n1speed")
    },

    rhs = function(step, y) {
      .Call("sir_base_rhs_r", private$ptr, step, y, PACKAGE = "h5n1speed")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("sir_base_contents", private$ptr, PACKAGE = "h5n1speed")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


sir_base <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("sir_base")
  sir_base_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(sir_base) <- "odin_generator"
attr(sir_base, "generator") <- sir_base_
sir_vaccine_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "sir_vaccine_rhs_dde"),
    dll = "h5n1speed",
    user = c("beta", "detect_n", "gamma", "I_ini", "intervention_scenario",
             "kappa", "nsim", "S_ini", "steps_per_day", "t_intervention",
             "zeta"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("sir_vaccine_rhs_dde", package = "h5n1speed")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("sir_vaccine_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "h5n1speed")
    },

    update_metadata = function() {
      meta <- .Call("sir_vaccine_metadata", private$ptr,
                    PACKAGE = "h5n1speed")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("sir_vaccine_create", user, PACKAGE = "h5n1speed")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/sir_vaccine.json", mustWork = TRUE,
                             package = "h5n1speed")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("sir_vaccine_set_user", private$ptr, user, PACKAGE = "h5n1speed")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("sir_vaccine_initial_conditions", private$ptr, step, PACKAGE = "h5n1speed")
    },

    rhs = function(step, y) {
      .Call("sir_vaccine_rhs_r", private$ptr, step, y, PACKAGE = "h5n1speed")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("sir_vaccine_contents", private$ptr, PACKAGE = "h5n1speed")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


sir_vaccine <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("sir_vaccine")
  sir_vaccine_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(sir_vaccine) <- "odin_generator"
attr(sir_vaccine, "generator") <- sir_vaccine_
